#!/usr/bin/env python
# CPU and Memory utilization on host by VM for Nagios
#
# Author: Rohit Agarwalla <roagarwa@cisco.com>

import argparse
import sys
import subprocess

STATE_OK = 0
STATE_CRITICAL = 1

parser = argparse.ArgumentParser(description='Check VM CPU and Memory utilization on Host')
args = parser.parse_args()


def get_vals():
    output = ''
    cmd = ["ps", "a", "u", "x"]
    try:
        f_cmd_output = subprocess.Popen(cmd, stdout=subprocess.PIPE).communicate()[0]
        ps = [lines for lines in f_cmd_output.splitlines() if "kvm" in lines]
        ps = [lines for lines in ps if "instance" in lines]
        retval = []
        for p in ps:
            processes = p.split('\n')
            nfields = len(processes[0].split()) - 1
            for row in processes:
                retval.append(row.split(None, nfields))
        return retval
    except Exception as e:
        print "CRITICAL -" + str(e)
        sys.exit(STATE_CRITICAL)

if __name__ == '__main__':
    return_output = ''
    output = get_vals()
    for out in output:
        proc_met = "Instance: " + out[20] + ", PID: " + out[1] + ", CPU: " + out[2] + "%" + ", Memory: " + out[3] + "%"
        #return_output += " \n " + proc_met
        return_output += " " + proc_met
    print "OK - " + return_output
    sys.exit(STATE_OK)
